name: Automated API tests using Postman CLI

on:
  workflow_call:

    inputs:
      environment-name:
        required: true
        type: string

jobs:
  automated-api-tests:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "545059-2c582470-9517-4b76-b4fd-5e4471d484ca" \
            --environment "545059-12d53539-7fef-47bd-a67b-3930310e69e2" \
            --integration-id "132187-${{ github.run_id }}" \
            --verbose
          # Lint your API using Postman CLI
          postman api lint --integration-id 132187
