
name: Java CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    name: Deploy
    uses: ./.github/workflows/deployment.yml
    if: ${{ github.ref_name == 'master' || startsWith(github.head_ref, 'feature/') }}
    with:
      environment-name: ${{ github.ref_name == 'master' && 'production' ||  'development' }}
      aws-region: us-east-1
    secrets: inherit
    needs: build

  test-api:
    name: Automated API tests
    uses: ./.github/workflows/api-tests.yml
    with:
      environment-name: ${{ github.ref_name == 'master' && 'production' ||  'development' }}
      api-url: ${{ needs.deploy.outputs.api-url }}
    secrets: inherit
    needs: deploy
